- README.md
- config/samples/cluster-deployment/gcp/gcp-cluster.yaml
- config/samples/cluster-deployment/gcp/gcp-controlplane.yaml
- config/samples/cluster-deployment/gcp/gcp-workers.yaml
- docs/GCP.md
This PR will add an initial doc for using the bootstrap provider with
GCP.
> feat: add docs and samples for GCP

- .drone.yml
- Dockerfile
- Makefile
> feat: add drone ci

- Dockerfile
- Makefile
- controllers/talosconfig_controller.go
- go.mod
- go.sum
> This PR updates the talos import so we can ensure we've got the latestmachine config generation logic

- controllers/secrets.go
- controllers/talosconfig_controller.go
- go.mod
- go.sum
> fix: better secret detection and update talos

- .gitignore
- Dockerfile
Make release needed a small tweak to its path.
> fix: update make release

- controllers/secrets.go
- controllers/talosconfig_controller.go
This PR will create a new secret called `$cluster_name-ca` that holds
certs that were generated for kubernetes. Cluster API uses these certs
to create a kubeconfig for the cluster. Additionally, in exploring this,
I discovered that we should be adding owners to our secrets so that they
get deleted automatically upon cluster deletion.
> fix: create secret with kube certs and cleanup talos secret

- config/metadata/metadata.yaml
This was missed in the previous PR.
> fix: update metadata.yaml for v0.2.0

- .drone.yml
This enables us to run in the new kube pipeline types.
> chore: update drone pipeline type

- CHANGELOG.md
- hack/chglog/CHANGELOG.tpl.md
- hack/chglog/config.yml
- hack/release.sh
This is the official v0.2.0-alpha.2 release.
> release(v0.2.0-alpha.2): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.3 release.
> release(v0.2.0-alpha.3): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.4 release.
> release(v0.2.0-alpha.4): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.5 release.
> release(v0.2.0-alpha.5): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.6 release.
> release(v0.2.0-alpha.6): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.7 release.
> release(v0.2.0-alpha.7): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.8 release.
> release(v0.2.0-alpha.8): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.9 release.
> release(v0.2.0-alpha.9): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.10 release.
> release(v0.2.0-alpha.10): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.11 release.
> release(v0.2.0-alpha.11): prepare release

- CHANGELOG.md
This is the official v0.2.0-alpha.12 release.
> release(v0.2.0-alpha.12): prepare release

- CHANGELOG.md
This is the official v0.2.0-beta.0 release.
> release(v0.2.0-beta.0): prepare release

- LICENSE
To make GitHub, pkg.go.dev, etc happy.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: add missing LICENSE file

- .drone.yml
> chore: sign Drone CI configuration

- .codecov.yml
- .drone.yml
- .gitignore
- Dockerfile
- Makefile
- internal/integration/integration_test.go
- internal/integration/setup_test.go
* run subtests in parallel;
* enabled race detector;
* enable codecov.io integration.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: improve tests runner

- .drone.yml
> chore: do not run tests on ARM

- .codecov.yml
- Makefile
Also tweak codecov configuration.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: use codecov uploader from build-container

- Dockerfile
- Makefile
> chore: make versions configurable

- internal/integration/setup_test.go
That makes tests more stable.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> test: wait for CAPI availability

- Makefile
- controllers/talosconfig_controller.go
- go.mod
- go.sum
- internal/integration/helpers_test.go
- internal/integration/integration_test.go
- internal/integration/setup_test.go
> test: add more tests

- internal/integration/helpers_test.go
- internal/integration/integration_test.go
> test: add test for the second machine

- CHANGELOG.md
This is the official v0.3.0-alpha.1 release.
> release(v0.3.0-alpha.1): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.3.0 release.
> release(v0.3.0): prepare release

- controllers/talosconfig_controller.go
- go.mod
- go.sum
- internal/integration/assertions_test.go
- internal/integration/integration_test.go
> backports: for 0.3.1 release

- CHANGELOG.md
- hack/release.toml
This is the official v0.3.1 release.
> release(v0.3.1): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.0-alpha.0 release.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>
> release(v0.4.0-alpha.0): prepare release

- .conform.yaml
- CHANGELOG.md
- hack/release.toml
This is the official v0.4.0 release.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>
> release(v0.4.0): prepare release

- .conform.yaml
- CHANGELOG.md
- hack/release.toml
This is the official v0.5.0 release.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>
> release(v0.5.0): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.3 release.
> release(v0.4.3): prepare release

- config/manager/manager.yaml
- main.go
This is using standard webhook-based checks.
> feat: add readiness/liveness checks

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.2 release.
> release(v0.5.2): prepare release

- .conform.yaml
This PR fixes the GPG check
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> chore: update GPG org

- README.md
> docs: update README for Talos 1.0

- Makefile
- go.mod
- go.sum
Update to the final released version.
> feat: update to Talos 1.2.0

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.6 release.
> release(v0.5.6): prepare release

- .conform.yaml
- CHANGELOG.md
- hack/release.sh
- hack/release.toml
- internal/integration/README.md
This is the official v0.6.0-alpha.0 release.
> release(v0.6.0-alpha.0): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.1 release.
> release(v0.6.1): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.2 release.
> release(v0.6.2): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.3 release.
> release(v0.6.3): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.4 release.
> release(v0.6.4): prepare release

- CHANGELOG.md
This is the official v0.6.5 release.
> release(v0.6.5): prepare release

- config/crd/patches/webhook_in_talosconfigs.yaml
- config/crd/patches/webhook_in_talosconfigtemplates.yaml
See https://github.com/kubernetes-sigs/cluster-api/pull/10972
> fix: remove CA bundle

- CHANGELOG.md
This is the official v0.6.7 release.
> release(v0.6.7): prepare release
