- controllers/secrets.go
- controllers/talosconfig_controller.go
- go.mod
- go.sum
This PR will pull in the latest talos release. This will fix the issue
of talos getting short, 24h certs. Which isn't a big deal for e2e but
causes some pain when doing demos of talos.
> chore: update talos to v0.3.0-alpha.8

- config/rbac/role_binding.yaml
There was a naming error in the rolebinding yamls. This will ensure
they'll get prefaced with the proper `cabpt-` string and work properly.
> fix: update name for rolebinding

- Dockerfile
- README.md
- config/metadata/metadata.yaml
This PR will move to publishing `bootstrap-components.yaml` and
`metdata.yaml` upon tagging a release so that clusterctl can consume
them.
> feat: add new release process

- controllers/talosconfig_controller.go
This PR does a check if we're dealing with a PacketMachine. If so, we
prepend the shebang necessary to make userdata work there.
> fix: ensure machine configs work in packet

- controllers/secrets.go
This PR fixes a bug where the bootstrap provider didn't own the certs it
created, they were owned by the cluster instead. This leads to a
case where, if control plane machines were cleaned up, the CA secret was
still present. I've moved ownership to be the TalosConfig and updated
how I set those owners based on what the kubeadm bootstrapper does.
I crosschecked what the owner is supposed to be by running this function
down: https://github.com/kubernetes-sigs/cluster-api/blob/v0.3.8/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L376
Will close #27
> fix: ensure proper ownership of certs

- controllers/talosconfig_controller.go
This PR adds a simple fix to strip the leading v before generating talos
machine configs if necessary.
> fix: change k8s version if it has leading "v"

- controllers/talosconfig_controller.go
- pkg/constants/constants.go
This PR fixes a bug where the pointer to the version string could be nil
and we were trying to call a TrimPrefix on the contents, causing a
panic. This now introduces a default kube version constant that will be
overridden if the version pointer is not nil.
> fix: ensure version is not nil

- controllers/talosconfig_controller.go
- go.mod
- go.sum
- pkg/constants/constants.go
This PR pulls in the latest machinery code from talos and fixes an
issue where we weren't providing a default DNS domain for talos config
generation. We now rely on the constants package inside of machinery for
a default dns name, as well as k8s version.
> fix: ensure we have a dns domain

- controllers/secrets.go
This PR fixes a bug where certain secrets should be cluster scoped b/c they get reused for
bootstrap data generation when new machines scale up/down.
> fix: make sure secrets are cluster owned

- go.mod
- go.sum
This PR updates the go mod import for talos machinery so we know about
the new DHCP options.
> chore: update talos machinery v0.7.0-alpha.7

- controllers/talosconfig_controller.go
This PR fixes a small bug where, when using configPatches, we weren't
injecting the `#!talos` string to the top of the machine config if
we were uisng Packet/Equinix.
> fix: ensure proper ordering of packet machine config handling

- config/manager/manager.yaml
This PR makes sure we set the machine pool flag for our bootstrap
provider. This is needed to make sure we work out of the box with ASGs
in AWS when users install our providers w/ clusterctl.
> feat: support EXP_MACHINE_POOL flag

- controllers/secrets.go
This PR fixes a bug where we left cert secrets behind after a cluster
was deleted. This led to a case where clusters created with the same
name would have issues.
> fix: ensure secrets are deleted when cluster is dropped

- config/manager/manager.yaml
This fixes an issue where we can't install on a 2 CPU/2GB RAM
node. Backing down the requests so that the pods can get scheduled, but
still keeping the limits high
> fix: back down resource requests

- config/metadata/metadata.yaml
This PR makes sure we'll generate a working metadata for clusterctl to
use for the v0.3 release series.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> fix: update metadata.yaml for v0.3 of CABPT

- controllers/secrets.go
- controllers/talosconfig_controller.go
- go.sum
- internal/integration/helpers_test.go
The one provided in the config owner spec is only used for pivoting.
> fix: construct properly data secret name

- go.mod
- go.sum
- internal/integration/assertions_test.go
This includes machine's CA distrituted to worker nodes.
Tests were updated to assert that.
Should be backported to 0.3.x.
> feat: bump Talos machinery to 0.12.3

- controllers/talosconfig_controller.go
- internal/integration/integration_test.go
Fixes #97
Skip creating the secret if the supplied user config doesn't have full
cluster CA. Cluster secret will be created once the controlplane machine
configuration is passed in.
> fix: don't write incomplete `<cluster>-ca` secret for configtype none

- config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigs.yaml
- config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigtemplates.yaml
- internal/integration/helpers_test.go
Now as we have core CAPI controllers running, they will do it
automatically which provides better test coverage.
> test: don't set the talosconfig owner ref to the machine

- .drone.yml
- Makefile
- config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigs.yaml
Add dirtiness check so that we will never have outdated manifests.
(cherry picked from commit f6dc0a3372dba82306a4abc9b2a064f1e337421c)
> fix: regenerate manifests

- controllers/talosconfig_controller.go
This PR fixes a small bug where we weren't correctly searching for `Kind` of `PacketMacine`
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> fix: ensure shebang on packet machine configs

- go.mod
- go.sum
- hack/clusterctl.yaml
- internal/integration/setup_test.go
Remove the temporary fix for cert-manager download.
> chore: bump CAPI to 1.0.4

- config/certmanager/certificate.yaml
- config/default/kustomization.yaml
Bump cert-manager to `v1`
Signed-off-by: Noel Georgi <git@frezbo.dev>
> chore: bump cert-manager to v1

- README.md
This PR adds a blurb for overriding the clusterctl yaml to work after
our rename
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> docs: add note for clusterctl rename bug

- api/v1alpha3/talosconfig_webhook.go
- api/v1alpha3/talosconfigtemplate_webhook.go
- config/webhook/manifests.yaml
- internal/integration/integration_test.go
- internal/integration/setup_test.go
This change is made to conform CAPI practices for resource updates:
instead of modifying the templates/configs, it is necessary to create a
new one.
If the resource is always recreated, rolling update strategy will be
able to pick up the change and redeploy machines.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>
> feat: make `talosconfig` and `talosconfigtemplate` immutable

- .gitignore
- config/manager/kustomization.yaml
- tilt-provider.json
This adds the support for [Tilt](https://tilt.dev), as described in https://cluster-api.sigs.k8s.io/developer/tilt.html#tilt-provider-configuration
Signed-off-by: Benjamin Gentil <benjamin.gentil@infomaniak.com>
> feat: add Tilt support

- config/metadata/metadata.yaml
This should fix the installation process.
> chore: add 0.6 series to CAPI metadata

- Makefile
- go.mod
- go.sum
This brings in a fix for `talosconfig` lifetime.
> fix: update Talos machinery to 1.5.2

- README.md
- api/v1alpha3/talosconfig_types.go
- api/v1alpha3/zz_generated.deepcopy.go
- config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigs.yaml
- config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigtemplates.yaml
- controllers/talosconfig_controller.go
- hack/release.toml
- internal/integration/integration_test.go
This commit implements strategic merge patch by reusing talos StrategicMergePatch implementation. Additionally, it adds an integration test for strategic merge patches.
Fixes https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/issues/181.
> feat: support for strategic merge patches

- controllers/talosconfig_controller.go
- internal/integration/assertions_test.go
- internal/integration/integration_test.go
> fix: generate configs without comments/examples

- controllers/talosconfig_controller.go
Use net.JoinHostPort to create endpoint URL, as this covers also the IPv6 address case, where the address needs to be enclosed in brackets. Otherwise use of IPv6 endpoint IPs will lead to an error.
> fix: use net.JoinHostPort for control plane endpoint URL

- .github/workflows/ci.yaml
- .kres.yaml
Build both amd64 and arm64 images on tag event.
Fixes: #214
> fix(ci): arm64 container image asset

- CHANGELOG.md
- hack/release.toml
This is the official v0.6.9 release.
> release(v0.6.9): prepare release
